title: Colin's GitHub Page
author: Colin Enos
email: colin.enos10@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Site is under construction

# social links
github_username:  cenos10

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
